# Generated by Django 4.0.3 on 2022-03-27 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_created_on_car_sold_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mobile',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
