# Generated by Django 4.0.3 on 2022-03-27 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_buycar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycar',
            name='mobile',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
